Revert "paste: Command to paste at bin.msfjarvis.dev"
This reverts commit 3c90e87da9691812e88065e8213cb5979e523c9f.

Signed-off-by: Harsh Shandilya <msfjarvis@gmail.com>

diff --git a/hastebin b/hastebin
--- a/hastebin
+++ b/hastebin
@@ -8,14 +8,14 @@ SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
 # shellcheck source=system
 source "${SCRIPT_DIR}"/system
 
-result=$(curl -sf -X POST -H "Content-Type: text/plain" --data-binary @"${1:--}" https://bin.msfjarvis.dev) || {
-  echo "ERROR: failed to post document" >&2
-  exit 1
+result=$(curl -sf --data-binary @"${1:--}" --header "X-api-key: ${DOGBIN_API_KEY}" https://del.dog/documents) || {
+    echo "ERROR: failed to post document" >&2
+    exit 1
 }
-
-trimmed="https://bin.msfjarvis.dev$(echo "$result" | awk '{print $4}')"
+key=$(jq -r .key <<<"${result}")
+url="https://del.dog/raw/${key}"
 if [ "$(display_exists)" ]; then
-  echo "$trimmed" | xclip -rmlastnl -selection clipboard
+    echo "$url" | xclip -rmlastnl -selection clipboard
 else
-  echo "$trimmed"
+    echo "$url"
 fi
