treewide: Reformat
Signed-off-by: Harsh Shandilya <msfjarvis@gmail.com>

diff --git a/hastebin b/hastebin
--- a/hastebin
+++ b/hastebin
@@ -4,14 +4,14 @@
 # SPDX-License-Identifier: GPL-3.0-only
 
 # Source common functions
-SCRIPT_DIR="$(cd "$( dirname "$( readlink -f "${BASH_SOURCE[0]}" )" )" && pwd)"
+SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
 source "${SCRIPT_DIR}"/system
 
 result=$(curl -sf --data-binary @"${1:--}" https://del.dog/documents) || {
-      echo "ERROR: failed to post document" >&2
-      exit 1
+    echo "ERROR: failed to post document" >&2
+    exit 1
 }
-key=$(jq -r .key <<< "${result}")
+key=$(jq -r .key <<<"${result}")
 url="https://del.dog/raw/${key}"
 if [ "$(display_exists)" ]; then
     echo "$url" | xclip -rmlastnl -selection clipboard
