hastebin: Reformat
Signed-off-by: Harsh Shandilya <me@msfjarvis.dev>

diff --git a/hastebin b/hastebin
--- a/hastebin
+++ b/hastebin
@@ -9,13 +9,13 @@ SCRIPT_DIR="$(cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd)"
 source "${SCRIPT_DIR}"/system
 
 result=$(curl -sf --data-binary @"${1:--}" --header "X-api-key: ${DOGBIN_API_KEY}" https://del.dog/documents) || {
-    echo "ERROR: failed to post document" >&2
-    exit 1
+  echo "ERROR: failed to post document" >&2
+  exit 1
 }
 key=$(jq -r .key <<<"${result}")
 url="https://del.dog/raw/${key}"
 if [ "$(display_exists)" ]; then
-    echo "$url" | xclip -rmlastnl -selection clipboard
+  echo "$url" | xclip -rmlastnl -selection clipboard
 else
-    echo "$url"
+  echo "$url"
 fi
